services:
  app:
    build:
      dockerfile: Dockerfile
      target: development
    image: nka-web
    volumes:
      - ..:/var/www/html
    container_name: nka-app
    # Linux only
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 80:8000
  database:
    image: neo4j:5.6
    ports:
      - 7474:7474 # Web interface
    container_name: nka-database
    volumes:
      - ./database/data:/data

networks:
  default:
    name: nka
    driver: bridge
